name: Sync Content

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd scripts
          pip install -r requirements.txt

      - name: Run sync script
        run: python scripts/main.py
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CC_CHAT_TOKEN: ${{ secrets.CC_CHAT_TOKEN }}

      - name: Commit updated seen_urls.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/seen_urls.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update seen URLs [skip ci]"
          git push
